### ISSUE TITLE
[Feature]: Authoritative IAM Binding Resources Causing Configuration Drift

### ISSUE THREAD

**Issue by jrsdav** [anyscale/terraform-google-anyscale-cloudfoundation-modules#26]
## Problem Description

The current use of authoritative `*_iam_binding` resources in this Terraform module is causing circular configuration drift issues when used in conjunction with our existing infrastructure and IAM management practices.

Specifically:

1. We use IAM roles such as `roles/storage.objectAdmin` and `roles/artifactregistry.reader` across various resources in our Google Cloud environment.
2. The Anyscale module uses `*_iam_binding` resources, which are authoritative and overwrite existing IAM policies.
3. Our downstream modules use `*_iam_member` against some of the same roles and resources (e.g., buckets and project-level permissions).
4. This setup creates a perpetual state of circular configuration drift as the Anyscale module runs and downstream modules react.

## Impact

1. Continuous configuration drift between Anyscale module runs and our existing IAM management.
2. Difficulty in maintaining our Terraform configuration for Anyscale due to existing Policy as Code that restricts the use of `*_iam_binding` in certain instances.
3. Potential risk of inadvertently cutting off access to shared resources.

## Investigation

After reviewing the Terraform code in this module's repository, we haven't found a clear justification for the use of `*_iam_binding` resources. While it's understandable to use these for complete control over which principals are allowed specific roles on the module's resources, it doesn't appear to be necessary in this case.

## Proposed Solution
Consider replacing the `*_iam_binding` resources with `*_iam_member` resources in the module. This change would allow:

1. More flexible integration with existing IAM policies and practices.
2. Reduction of configuration drift issues.
3. Better compatibility with Policy as Code practices that restrict the use of authoritative IAM bindings.

## Questions

Is there a specific reason for using `*_iam_binding` resources in this module that we might have overlooked?
Would it be feasible to switch to `*_iam_member` resources, or provide an option to choose between the two approaches?

We appreciate your consideration of this issue and look forward to your thoughts on how we can best resolve these IAM conflicts.

### Which module(s)?

- [X] Root Anyscale Module
- [ ] google-anyscale-cloudapis
- [ ] google-anyscale-cloudstorage
- [ ] google-anyscale-filestore
- [ ] google-anyscale-iam
- [ ] google-anyscale-project
- [ ] google-anyscale-vpc
- [ ] google-anyscale-vpc-firewall

### Is it blocking work?

no

### Terraform version

None

**Comment by hongchaodeng** [comment]
I'm taking a look

**Comment by brent-anyscale** [comment]
Please let us know if you continue to see drift!
